Create SECURITY.md
bis-med-it/SDMX-dashboard-generator pull request #50
Opened 2024-02-28 09:57 UTC by stephprobst

Adds a security md file to be in line with best practices. The proposed security md file was copied from the pysdmx project.

2024-02-28 10:01 UTC, osirello requested changes

2024-02-28 10:01 UTC, osirello commented on SECURITY.md
> +## Security Patch Release Process
I would expressly mention also paragraph 3 of Licence (No warranty of support)

2024-02-28 10:07 UTC, stephprobst commented on SECURITY.md
> +## Security Patch Release Process
Done. I added it to the top of the file.

2024-02-29 03:55 UTC, pietropatelli approved these changes

2024-03-26 13:09 UTC, osirello approved these changes

2024-03-26 13:11 UTC, merged